version: '3'
services:
  clash:
    image: dreamacro/clash
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
      # dashboard volume
      - ./ui:/ui
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090"
      # If you need external controller, you can export this port.
      # - "8080:8080"
    restart: always
    # When your system is Linux, you can use `network_mode: "host"` directly.
    network_mode: "host"
    container_name: clash

  yacd:
    image: haishanh/yacd
    ports:
      - "1234:80"
    restart: always
    container_name: yacd
